version: '3.4'

services:
  testmasstransit:
    image: ${DOCKER_REGISTRY-}testmasstransit
    depends_on: 
        - activemq
    build:
      context: .
      dockerfile: Dockerfile

  activemq:
    image: rmohr/activemq:5.15.9
    container_name: activemq
    hostname: activemq
    ports: 
      - "8161:8161"
      - "61616:61616"